# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{to_pass}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthias Viehweger"]
  s.date = %q{2010-08-09}
  s.description = %q{Passwords should be easy to remember and hard to guess.
One technique is to have a sentence which can be easily remembered transformed to a password.}
  s.email = %q{kronn@kronn.de}
  s.executables = ["password_of", "to_pass"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/password_of",
     "bin/to_pass",
     "lib/to_pass.rb",
     "lib/to_pass/algorithm_reader.rb",
     "lib/to_pass/algorithms/basic_de.yml",
     "lib/to_pass/algorithms/basic_en.yml",
     "lib/to_pass/algorithms/secure.yml",
     "lib/to_pass/base.rb",
     "lib/to_pass/cli.rb",
     "lib/to_pass/converter.rb",
     "lib/to_pass/converter_reader.rb",
     "lib/to_pass/converters.rb",
     "lib/to_pass/converters/collapse_chars.rb",
     "lib/to_pass/converters/downcase.rb",
     "lib/to_pass/converters/expand_below.rb",
     "lib/to_pass/converters/first_chars.rb",
     "lib/to_pass/converters/remove_repetition.rb",
     "lib/to_pass/converters/replace.rb",
     "lib/to_pass/converters/reverse.rb",
     "lib/to_pass/converters/swapcase.rb",
     "lib/to_pass/integration.rb",
     "man/index.txt",
     "man/to_pass-algorithm.5",
     "man/to_pass-algorithm.5.html",
     "man/to_pass-algorithm.5.ronn",
     "man/to_pass-converter.5",
     "man/to_pass-converter.5.html",
     "man/to_pass-converter.5.ronn",
     "man/to_pass.1",
     "man/to_pass.1.html",
     "man/to_pass.1.ronn",
     "test/fixtures/user_alg.yml",
     "test/fixtures/user_converter.rb",
     "test/helper.rb",
     "test/test_algorithm_reader.rb",
     "test/test_algorithms.rb",
     "test/test_base.rb",
     "test/test_cli.rb",
     "test/test_converter.rb",
     "test/test_converter_reader.rb",
     "test/test_converters.rb",
     "test/test_integration.rb"
  ]
  s.homepage = %q{http://github.com/kronn/to_pass}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{generate password from words or sentences}
  s.test_files = [
    "test/fixtures/user_converter.rb",
     "test/helper.rb",
     "test/test_algorithm_reader.rb",
     "test/test_algorithms.rb",
     "test/test_base.rb",
     "test/test_cli.rb",
     "test/test_converter.rb",
     "test/test_converter_reader.rb",
     "test/test_converters.rb",
     "test/test_integration.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<sdoc>, [">= 0"])
    else
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<sdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<sdoc>, [">= 0"])
  end
end

